[package]
name = "boyermoore_implementations_nif"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "boyermoore_implementations_nif"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.25.0"
